import Header from '@/components/Header';
import './globals.css'
import { Roboto } from 'next/font/google';
import Footer from '@/components/Footer'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: "SpaceSage Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-slate-800 text-white`}>
        <Header />
        <main>
          {children}
        </main>
      <Footer />
      </body>
    </html>
  )
}
// 